### ISSUE TITLE
About datasets scale

### ISSUE THREAD

**Issue by LYnini** [YilanDong19/Machine-learning-with-ABIDE#3]
Hello, I saw on the official website of ABIDEdataset that there are 1112 samples in the detailed introduction. Why did you use only 871 samples during training? Thank you!

**Comment by YilanDong19** [comment]
> Hello, I saw on the official website of ABIDEdataset that there are 1112 samples in the detailed introduction. Why did you use only 871 samples during training? Thank you!

Thanks for your interest. As you can see, in the folder Data_download_prepare, there is a file called subject_IDs.txt, which contains 871 samples' ID. This list comes from paper '**Deriving reproducible biomarkers from multi-site resting-state data: AnAutism-based example**', Abraham selected these 871 relatively high-quality data from ABIDE I dataset. Since then, this list has been widely used in many experiments. In order to compare the performance between models, I also chose this widely used list.
'
